language: go

go: 
- 1.12.x

jobs:
  include:
    - script:  go build ./go/hello-world/.
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: 4b601a9d381019dd6cf3996054c66820a3ac0be2
        skip_cleanup: true
        on:
          tags: true
