language: go

go: 
- 1.12.x

jobs:
  include:
    - script:  go build ./go/hello-world/.
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: "a1e4b79228eb74dc499d2e86a1234dfb93871323"
        skip_cleanup: true
        on:
          tags: true
